### PR TITLE
add reference to reason behind calibration procedure

### PR DESCRIPTION
**Pull request by hosnerm**
@tanij the wanted reference to the calibration procedure as talked about yesterday

### CODE REVIEW

**Comment by AmaurX** [comment]
@hosnerm  can you push that to daffy-devel? It will be easier to merge all in daaf-devel then do on PR on daffy

**Comment by hosnerm** [comment]
this is old stuff from RH1. will not interfere with current developed things. So: no, will not

**Comment by AmaurX** [comment]
That is not the reason, I say that because it is not urgent to merge, and merging the PR on daffy one by one will take ages. 
I  dont see the issue to put it in daffy devel anyways

**Comment by hosnerm** [comment]
i do not really see your point but i can do it if it is your deep desire

**Pull request closed without merging**
